export type ResourceType = "pdf" | "video" | "link" | "graphic"

export interface Resource {
  id: string
  title: string
  type: ResourceType
  url: string
  thumbnail: string
  summary: string
  tags: string[]
  dateAdded: string
  author?: string
  year?: number // Publication year
  localPath?: string // For locally uploaded PDFs (temporary, local only)
  ratingSum?: number // Sum of all user ratings
  ratingCount?: number // Number of ratings
  userRating?: number // Current user's rating (1-4)
}

export const resources: Resource[] = [
  {
    id: "1770143100001-c0p1l0t",
    title: "Microsoft Copilot",
    type: "link",
    url: "https://copilot.microsoft.com/",
    thumbnail: "https://copilot.microsoft.com/static/cmc/images/meta-image.jpg",
    summary: "A conversational AI interface from Microsoft that integrates ChatGPT capabilities for general productivity and search.",
    tags: ["Ai Companion", "Chatgpt", "Productivity"],
    dateAdded: "2026-02-03",
    author: "Microsoft",
    year: 2023,
  },
  {
    id: "1770143100002-d1ff1tt",
    title: "Diffit",
    type: "link",
    url: "https://web.diffit.me/",
    thumbnail: "http://static1.squarespace.com/static/6417f1e0a6e26c5d06b65171/t/68dc72e70e64cd696d8bb939/1759277799106/Diffit+Logo.png?format=1500w",
    summary: "Creates leveled resources, vocabulary lists, and assessments for teachers to help differentiate instruction.",
    tags: ["Content Generation", "Differentiation"],
    dateAdded: "2026-02-03",
    author: "Diffit",
    year: 2023,
  },
  {
    id: "1770143100003-t3achally",
    title: "TeachAlly",
    type: "link",
    url: "https://www.teachally.com/",
    thumbnail: "https://teachally.com/wp-content/uploads/2025/08/images.png",
    summary: "Generates standard-aligned lesson plans, assignments, and presentations to save teacher prep time.",
    tags: ["Content Generation", "Lesson Planning"],
    dateAdded: "2026-02-03",
    author: "TeachAlly",
    year: 2023,
  },
  {
    id: "1770143100004-r0ck3ttai",
    title: "Rockettai",
    type: "link",
    url: "https://www.rockettai.com/",
    thumbnail: "https://rockettai.com/wp-content/uploads/2024/01/iap.jpg",
    summary: "A suite of educational tools including labs, worksheets, and slide decks for classroom use.",
    tags: ["Content Generation", "Worksheets"],
    dateAdded: "2026-02-03",
    author: "Rockettai",
    year: 2023,
  },
  {
    id: "1770143100005-th33ducat0r",
    title: "theEducator",
    type: "link",
    url: "https://www.theeducator.ai/",
    thumbnail: "https://theeducator.ai/wp-content/uploads/2025/04/cropped-cropped-aiAnnaIcon.png",
    summary: "Provides free tools for generating flashcards, student reports, and instructional presentations.",
    tags: ["Content Generation", "Flashcards"],
    dateAdded: "2026-02-03",
    author: "theEducator",
    year: 2023,
  },
  {
    id: "1770143100006-br1sk",
    title: "Brisk Teaching",
    type: "link",
    url: "https://www.briskteaching.com/",
    thumbnail: "https://cdn.prod.website-files.com/64d233e71a07f45ec32b6736/67361ffdadf0f75aeb490b71_Screenshot%202024-11-14%20180520.png",
    summary: "A browser extension that helps create lesson plans, quizzes, and translations within existing workflows.",
    tags: ["Content Generation", "Assessment"],
    dateAdded: "2026-02-03",
    author: "Brisk Teaching",
    year: 2023,
  },
  {
    id: "1770143100007-c1assx",
    title: "ClassX AI Lesson Creator",
    type: "link",
    url: "https://classx.org/ai-lesson-creator/",
    thumbnail: "https://classx.org/wp-content/uploads/2023/03/AI-Lesson-Creator.png",
    summary: "Specialized tool for the rapid creation of lesson materials and other educational resources.",
    tags: ["Content Generation", "Lesson Planning"],
    dateAdded: "2026-02-03",
    author: "ClassX",
    year: 2023,
  },
  {
    id: "1770143100008-s0crat",
    title: "Socrat",
    type: "link",
    url: "https://www.socrat.ai/",
    thumbnail: "",
    summary: "AI platform focused on improving classroom engagement through modern teaching and learning solutions.",
    tags: ["Content Generation", "Engagement"],
    dateAdded: "2026-02-03",
    author: "Socrat",
    year: 2022,
  },
  {
    id: "1770143100009-tbuddy",
    title: "TeachersBuddy",
    type: "link",
    url: "https://www.teachersbuddy.com/region/us",
    thumbnail: "",
    summary: "Assists in brainstorming, finding resources, explaining text, and creating assignment exemplars.",
    tags: ["Content Generation", "Curriculum Support"],
    dateAdded: "2026-02-03",
    author: "TeachersBuddy",
    year: 2023,
  },
  {
    id: "1770143100010-cha1k1e",
    title: "Chalkie",
    type: "link",
    url: "https://chalkie.ai/",
    thumbnail: "https://framerusercontent.com/assets/DowF9yGxTKgppe3EcuhWY30P3qk.png",
    summary: "Automates the production of activity sheets and lesson outlines using AI-driven generators.",
    tags: ["Content Generation", "Worksheets"],
    dateAdded: "2026-02-03",
    author: "Chalkie",
    year: 2023,
  },
  {
    id: "1770143100011-charact3r",
    title: "Character.ai",
    type: "link",
    url: "https://www.character.ai/",
    thumbnail: "https://character.ai/character-ai.jpg",
    summary: "Platform for interacting with AI personas, useful for historical reenactments, roleplay, and storytelling.",
    tags: ["Gamification", "Personas"],
    dateAdded: "2026-02-03",
    author: "Character.ai",
    year: 2022,
  },
  {
    id: "1770143100012-3dua1d3",
    title: "Eduaide.ai",
    type: "link",
    url: "https://www.eduaide.ai/",
    thumbnail: "",
    summary: "Comprehensive assistant that provides a lesson builder, educational games, and teaching organizers.",
    tags: ["Gamification", "Instructional Design"],
    dateAdded: "2026-02-03",
    author: "Eduaide",
    year: 2023,
  },
  {
    id: "1770143100013-m0nsha",
    title: "Monsha",
    type: "link",
    url: "https://monsha.ai/",
    thumbnail: "https://cdn.prod.website-files.com/67f7f7f50ddeef0ebca4c8de/6802319ce9f419ff729edb4d_og-image.png",
    summary: "AI tool designed for unit mapping and planning complex course designs with ease.",
    tags: ["Planning", "Curriculum Mapping"],
    dateAdded: "2026-02-03",
    author: "Monsha",
    year: 2023,
  },
  {
    id: "1770143100014-acad3m1q",
    title: "Academiq",
    type: "link",
    url: "https://academiq.io/",
    thumbnail: "https://academiq.io/logo.png",
    summary: "Focuses on personalized learning paths and lesson planning to tailor education to individual student needs.",
    tags: ["Planning", "Personalized Learning"],
    dateAdded: "2026-02-03",
    author: "Academiq",
    year: 2023,
  },
  {
    id: "1770143100015-l3arnt",
    title: "Learnt.ai",
    type: "link",
    url: "https://www.learnt.ai/",
    thumbnail: "https://8d430738bebb138a9947571b29f7ec0c.cdn.bubble.io/cdn-cgi/image/w=,h=,f=auto,dpr=1,fit=contain/f1672951757937x534762048887333700/Square%20Learnt.Ai%20logo.png",
    summary: "A toolkit for education professionals to streamline the planning and content creation process.",
    tags: ["Planning", "Instructional Design"],
    dateAdded: "2026-02-03",
    author: "Learnt.ai",
    year: 2023,
  },
  {
    id: "1770143100016-mag1c",
    title: "MagicSchool AI",
    type: "link",
    url: "https://www.magicschool.ai/",
    thumbnail: "https://cdn.prod.website-files.com/645187265d5e5e386be40629/697bb68ecc1cfed51a6ccef1_Open-graph_HOME.jpg",
    summary: "A massive platform for planning, differentiation, and student support, widely used in K-12 education.",
    tags: ["Planning", "K-12 Education"],
    dateAdded: "2026-02-03",
    author: "MagicSchool",
    year: 2023,
  },
  {
    id: "1770143100017-canva",
    title: "Canva Magic Studio",
    type: "link",
    url: "https://www.canva.com/",
    thumbnail: "",
    summary: "AI-powered design suite within Canva for generating presentations, images, and videos.",
    tags: ["Presentation Creation", "Visual Design"],
    dateAdded: "2026-02-03",
    author: "Canva",
    year: 2023,
  },
  {
    id: "1770143100018-gamma",
    title: "Gamma",
    type: "link",
    url: "https://gamma.app/",
    thumbnail: "",
    summary: "Creates beautiful presentations, documents, and webpages from text prompts in seconds.",
    tags: ["Presentation Creation", "Design"],
    dateAdded: "2026-02-03",
    author: "Gamma",
    year: 2023,
  },
  {
    id: "1770143100019-audi0p3n",
    title: "AudioPen",
    type: "link",
    url: "https://audiopen.ai/",
    thumbnail: "https://a7b19d7a245c07286533d7a21bca9acc.cdn.bubble.io/cdn-cgi/image/w=,h=,f=auto,dpr=1,fit=contain/f1689050506225x715036324823828100/Thumbnail%20New%20Jul%2011_v2.png",
    summary: "Converts spoken rambling into clear, structured text summaries, perfect for note-taking.",
    tags: ["Notes and Transcription", "Speech-to-Text"],
    dateAdded: "2026-02-03",
    author: "AudioPen",
    year: 2023,
  },
  {
    id: "1770143100020-11labs",
    title: "ElevenLabs",
    type: "link",
    url: "https://elevenlabs.io/",
    thumbnail: "https://elevenlabs.io/cover.png",
    summary: "AI audio platform capable of generating life-like voices for storytelling and accessibility.",
    tags: ["Notes and Transcription", "Voice Synthesis"],
    dateAdded: "2026-02-03",
    author: "ElevenLabs",
    year: 2022,
  },
  {
    id: "1770143100021-m33tg33k",
    title: "MeetGeek",
    type: "link",
    url: "https://www.meetgeek.ai/",
    thumbnail: "https://meetgeekpublic.s3.eu-west-1.amazonaws.com/meetgeek.ai/png/64c908e38efe9e6833b912e6_Open+Graph+Image+-+MeetGeek.png",
    summary: "Records and summarizes online meetings, emails, and calendars for efficient review.",
    tags: ["Notes and Transcription", "Summarization"],
    dateAdded: "2026-02-03",
    author: "MeetGeek",
    year: 2021,
  },
  {
    id: "1770143100022-synth3s1a",
    title: "Synthesia",
    type: "link",
    url: "https://www.synthesia.io/",
    thumbnail: "https://cdn.prod.website-files.com/65e89895c5a4b8d764c0d710/67dad5d5c238a51c2327e203_OG-Image_2025.jpg",
    summary: "Turns text input into high-quality video featuring AI avatars that \"speak\" the content.",
    tags: ["Video Creation", "Avatar Video"],
    dateAdded: "2026-02-03",
    author: "Synthesia",
    year: 2017,
  },
  {
    id: "1770143100023-h3yg3n",
    title: "HeyGen",
    type: "link",
    url: "https://www.heygen.com/",
    thumbnail: "https://cdn.sanity.io/images/pdhqcmb1/production/579e83ff34c4c832744efaedb9681d255e58dc13-1200x630.png?fit=max&auto=format",
    summary: "Create AI-generated avatar videos from text for educational and marketing purposes.",
    tags: ["Video Creation", "Avatar Video"],
    dateAdded: "2026-02-03",
    author: "HeyGen",
    year: 2020,
  },
  {
    id: "1770143100024-parlay",
    title: "Parlay",
    type: "link",
    url: "https://www.parlayideas.com/",
    thumbnail: "https://parlayideas.com/wp-content/themes/parlay14/images/share.jpg",
    summary: "Facilitates class discussions and tracks student engagement through data-driven insights.",
    tags: ["Discussion Assistants", "Classroom Management"],
    dateAdded: "2026-02-03",
    author: "Parlay",
    year: 2016,
  },
  {
    id: "1770143100025-tw33",
    title: "Twee",
    type: "link",
    url: "https://www.twee.com/",
    thumbnail: "",
    summary: "Designed for English teachers to create ESL worksheets, quizzes, and text summaries.",
    tags: ["Language Tools", "ESL"],
    dateAdded: "2026-02-03",
    author: "Twee",
    year: 2022,
  },
  {
    id: "1770143100026-l1ng0",
    title: "Lingo Teach",
    type: "link",
    url: "https://lingoteach.ai/",
    thumbnail: "https://lingoteach.ai/logo192.png",
    summary: "An AI platform built specifically to support language teachers with curriculum and content.",
    tags: ["Language Tools", "Foreign Languages"],
    dateAdded: "2026-02-03",
    author: "Lingo Teach",
    year: 2023,
  },
  {
    id: "1770143100027-t3achfx",
    title: "TeachFX",
    type: "link",
    url: "https://www.teachfx.com/",
    thumbnail: "https://framerusercontent.com/images/ZUVYv3hsUrEif0v6imx3ZRQjIJg.jpg",
    summary: "Analyzes classroom audio to provide feedback on student voice and teacher talk time.",
    tags: ["Language Tools", "Reflection"],
    dateAdded: "2026-02-03",
    author: "TeachFX",
    year: 2017,
  },
  {
    id: "1770143100028-scha1",
    title: "SchoolAI",
    type: "link",
    url: "https://schoolai.com/",
    thumbnail: "https://framerusercontent.com/images/Og1g9vg7LhVhFh5pw4i1Wb0R0.jpg",
    summary: "Includes an IEP goal generator, lesson plan tools, and personalized assistants for K-12 students.",
    tags: ["Language Tools", "IEP Support"],
    dateAdded: "2026-02-03",
    author: "SchoolAI",
    year: 2023,
  },
  {
    id: "1770143100029-handta1k",
    title: "Hand Talk",
    type: "link",
    url: "https://www.handtalk.me/en/app/",
    thumbnail: "",
    summary: "Translates text and audio into sign language using a 3D AI-powered avatar dictionary.",
    tags: ["Accessibility", "Sign Language"],
    dateAdded: "2026-02-03",
    author: "Hand Talk",
    year: 2012,
  },
  {
    id: "1770143100030-s331ngai",
    title: "Seeing AI",
    type: "link",
    url: "https://www.microsoft.com/en-us/ai/seeing-ai",
    thumbnail: "",
    summary: "Microsoft app that narrates the visual world for people with low vision by identifying people and objects.",
    tags: ["Accessibility", "Vision Support"],
    dateAdded: "2026-02-03",
    author: "Microsoft",
    year: 2017,
  },
  {
    id: "1770143100031-bra1nly",
    title: "Brainly",
    type: "link",
    url: "https://www.brainly.com/",
    thumbnail: "",
    summary: "Peer-to-peer tutoring network that uses AI to provide test prep and worksheet support.",
    tags: ["Student Tutoring", "Homework Help"],
    dateAdded: "2026-02-03",
    author: "Brainly",
    year: 2009,
  },
  {
    id: "1770143100032-khanm1g0",
    title: "Khanmigo",
    type: "link",
    url: "https://www.khanacademy.org/khanmigo",
    thumbnail: "",
    summary: "Khan Academy's AI tutor for students and assistant for teachers to support differentiation.",
    tags: ["Student Tutoring", "Socratic Learning"],
    dateAdded: "2026-02-03",
    author: "Khan Academy",
    year: 2023,
  },
  {
    id: "1770143100033-draftback",
    title: "Draftback",
    type: "link",
    url: "https://chrome.google.com/webstore/detail/draftback/icmlicpmgeokunaoenneenphkhdbdhki",
    thumbnail: "https://ssl.gstatic.com/chrome/webstore/images/chrome_web_store_v2_1200x630.png",
    summary: "Plays back the history of changes to a Google Doc to help track progress and detect plagiarism.",
    tags: ["Writing Assistants", "Integrity Tools"],
    dateAdded: "2026-02-03",
    author: "James Somers",
    year: 2014,
  },
  {
    id: "1770143100034-sparkspac3",
    title: "Sparkspace",
    type: "link",
    url: "https://www.sparkspace.ai/",
    thumbnail: "https://sparkspace.ai/sparkspace-logo.png",
    summary: "Provides real-time coaching for writing to improve student engagement and mastery.",
    tags: ["Writing Assistants", "Coaching"],
    dateAdded: "2026-02-03",
    author: "Sparkspace",
    year: 2024,
  },
  {
    id: "1770143100035-grammarly",
    title: "Grammarly",
    type: "link",
    url: "https://www.grammarly.com/",
    thumbnail: "https://static-web.grammarly.com/cms/master/public/open-graph/social-24.png",
    summary: "Widely used AI tool for grammar correction, tone adjustment, and writing improvement.",
    tags: ["Writing Assistants", "Grammar"],
    dateAdded: "2026-02-03",
    author: "Grammarly",
    year: 2009,
  },
  {
    id: "1770143100036-packback",
    title: "Packback",
    type: "link",
    url: "https://www.packback.co/",
    thumbnail: "https://packback.co/wp-content/uploads/2025/06/topimg-1.png",
    summary: "Inquiry-based discussion and writing feedback platform designed for higher ed and K-12.",
    tags: ["Writing Assistants", "Student Engagement"],
    dateAdded: "2026-02-03",
    author: "Packback",
    year: 2014,
  },
]

// Base popular tags are now dynamically generated from actual resource tags

export interface TagWithCount {
  tag: string
  count: number
}

// Get popular tags - generated from actual tags used in the library, sorted by frequency
// Only returns tags with more than 3 items
export const getPopularTags = (resourceList: Resource[] = resources, limit: number = 20): TagWithCount[] => {
  // Count tag frequency in resources
  const tagCounts: Record<string, number> = {}
  resourceList.forEach(resource => {
    resource.tags.forEach(tag => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1
    })
  })
  
  // Filter tags with more than 3 items, sort by frequency and return top tags
  return Object.entries(tagCounts)
    .filter(([_, count]) => count > 3)
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([tag, count]) => ({ tag, count }))
}
