export type ResourceType = "pdf" | "video" | "link" | "graphic"

export interface Resource {
  id: string
  title: string
  type: ResourceType
  url: string
  thumbnail: string
  summary: string
  tags: string[]
  dateAdded: string
  author?: string
  year?: number // Publication year
  localPath?: string // For locally uploaded PDFs (temporary, local only)
  ratingSum?: number // Sum of all user ratings
  ratingCount?: number // Number of ratings
  userRating?: number // Current user's rating (1-4)
}

export const resources: Resource[] = [
  {
    id: "1770143100001-c0p1l0t",
    title: "Microsoft Copilot",
    type: "link",
    url: "https://copilot.microsoft.com/",
    thumbnail: "https://copilot.microsoft.com/static/cmc/images/meta-image.jpg",
    summary: "A conversational AI interface from Microsoft that integrates ChatGPT capabilities for general productivity and search.",
    tags: ["Ai Companion", "Chatgpt", "Productivity"],
    dateAdded: "2026-02-03",
    author: "Microsoft",
    year: 2023,
  },
  {
    id: "1770143100002-d1ff1tt",
    title: "Diffit",
    type: "link",
    url: "https://web.diffit.me/",
    thumbnail: "http://static1.squarespace.com/static/6417f1e0a6e26c5d06b65171/t/68dc72e70e64cd696d8bb939/1759277799106/Diffit+Logo.png?format=1500w",
    summary: "Creates leveled resources, vocabulary lists, and assessments for teachers to help differentiate instruction.",
    tags: ["Content Generation", "Differentiation"],
    dateAdded: "2026-02-03",
    author: "Diffit",
    year: 2023,
  },
  {
    id: "1770143100003-t3achally",
    title: "TeachAlly",
    type: "link",
    url: "https://www.teachally.com/",
    thumbnail: "https://teachally.com/wp-content/uploads/2025/08/images.png",
    summary: "Generates standard-aligned lesson plans, assignments, and presentations to save teacher prep time.",
    tags: ["Content Generation", "Lesson Planning"],
    dateAdded: "2026-02-03",
    author: "TeachAlly",
    year: 2023,
  },
  {
    id: "1770143100004-r0ck3ttai",
    title: "Rockettai",
    type: "link",
    url: "https://www.rockettai.com/",
    thumbnail: "https://rockettai.com/wp-content/uploads/2024/01/iap.jpg",
    summary: "A suite of educational tools including labs, worksheets, and slide decks for classroom use.",
    tags: ["Content Generation", "Worksheets"],
    dateAdded: "2026-02-03",
    author: "Rockettai",
    year: 2023,
  },
  {
    id: "1770143100005-th33ducat0r",
    title: "theEducator",
    type: "link",
    url: "https://www.theeducator.ai/",
    thumbnail: "https://theeducator.ai/wp-content/uploads/2025/04/cropped-cropped-aiAnnaIcon.png",
    summary: "Provides free tools for generating flashcards, student reports, and instructional presentations.",
    tags: ["Content Generation", "Flashcards"],
    dateAdded: "2026-02-03",
    author: "theEducator",
    year: 2023,
  },
  {
    id: "1770143100006-br1sk",
    title: "Brisk Teaching",
    type: "link",
    url: "https://www.briskteaching.com/",
    thumbnail: "https://cdn.prod.website-files.com/64d233e71a07f45ec32b6736/67361ffdadf0f75aeb490b71_Screenshot%202024-11-14%20180520.png",
    summary: "A browser extension that helps create lesson plans, quizzes, and translations within existing workflows.",
    tags: ["Content Generation", "Assessment"],
    dateAdded: "2026-02-03",
    author: "Brisk Teaching",
    year: 2023,
  },
  {
    id: "1770143100007-c1assx",
    title: "ClassX AI Lesson Creator",
    type: "link",
    url: "https://classx.org/ai-lesson-creator/",
    thumbnail: "https://classx.org/wp-content/uploads/2023/03/AI-Lesson-Creator.png",
    summary: "Specialized tool for the rapid creation of lesson materials and other educational resources.",
    tags: ["Content Generation", "Lesson Planning"],
    dateAdded: "2026-02-03",
    author: "ClassX",
    year: 2023,
  },
  {
    id: "1770143100008-s0crat",
    title: "Socrat",
    type: "link",
    url: "https://www.socrat.ai/",
    thumbnail: "",
    summary: "AI platform focused on improving classroom engagement through modern teaching and learning solutions.",
    tags: ["Content Generation", "Engagement"],
    dateAdded: "2026-02-03",
    author: "Socrat",
    year: 2022,
  },
  {
    id: "1770143100009-tbuddy",
    title: "TeachersBuddy",
    type: "link",
    url: "https://www.teachersbuddy.com/region/us",
    thumbnail: "",
    summary: "Assists in brainstorming, finding resources, explaining text, and creating assignment exemplars.",
    tags: ["Content Generation", "Curriculum Support"],
    dateAdded: "2026-02-03",
    author: "TeachersBuddy",
    year: 2023,
  },
  {
    id: "1770143100010-cha1k1e",
    title: "Chalkie",
    type: "link",
    url: "https://chalkie.ai/",
    thumbnail: "https://framerusercontent.com/assets/DowF9yGxTKgppe3EcuhWY30P3qk.png",
    summary: "Automates the production of activity sheets and lesson outlines using AI-driven generators.",
    tags: ["Content Generation", "Worksheets"],
    dateAdded: "2026-02-03",
    author: "Chalkie",
    year: 2023,
  },
  {
    id: "1770143100011-charact3r",
    title: "Character.ai",
    type: "link",
    url: "https://www.character.ai/",
    thumbnail: "https://character.ai/character-ai.jpg",
    summary: "Platform for interacting with AI personas, useful for historical reenactments, roleplay, and storytelling.",
    tags: ["Gamification", "Personas"],
    dateAdded: "2026-02-03",
    author: "Character.ai",
    year: 2022,
  },
  {
    id: "1770143100012-3dua1d3",
    title: "Eduaide.ai",
    type: "link",
    url: "https://www.eduaide.ai/",
    thumbnail: "",
    summary: "Comprehensive assistant that provides a lesson builder, educational games, and teaching organizers.",
    tags: ["Gamification", "Instructional Design"],
    dateAdded: "2026-02-03",
    author: "Eduaide",
    year: 2023,
  },
  {
    id: "1770143100013-m0nsha",
    title: "Monsha",
    type: "link",
    url: "https://monsha.ai/",
    thumbnail: "https://cdn.prod.website-files.com/67f7f7f50ddeef0ebca4c8de/6802319ce9f419ff729edb4d_og-image.png",
    summary: "AI tool designed for unit mapping and planning complex course designs with ease.",
    tags: ["Planning", "Curriculum Mapping"],
    dateAdded: "2026-02-03",
    author: "Monsha",
    year: 2023,
  },
  {
    id: "1770143100014-acad3m1q",
    title: "Academiq",
    type: "link",
    url: "https://academiq.io/",
    thumbnail: "https://academiq.io/logo.png",
    summary: "Focuses on personalized learning paths and lesson planning to tailor education to individual student needs.",
    tags: ["Planning", "Personalized Learning"],
    dateAdded: "2026-02-03",
    author: "Academiq",
    year: 2023,
  },
  {
    id: "1770143100015-l3arnt",
    title: "Learnt.ai",
    type: "link",
    url: "https://www.learnt.ai/",
    thumbnail: "https://8d430738bebb138a9947571b29f7ec0c.cdn.bubble.io/cdn-cgi/image/w=,h=,f=auto,dpr=1,fit=contain/f1672951757937x534762048887333700/Square%20Learnt.Ai%20logo.png",
    summary: "A toolkit for education professionals to streamline the planning and content creation process.",
    tags: ["Planning", "Instructional Design"],
    dateAdded: "2026-02-03",
    author: "Learnt.ai",
    year: 2023,
  },
  {
    id: "1770143100016-mag1c",
    title: "MagicSchool AI",
    type: "link",
    url: "https://www.magicschool.ai/",
    thumbnail: "https://cdn.prod.website-files.com/645187265d5e5e386be40629/697bb68ecc1cfed51a6ccef1_Open-graph_HOME.jpg",
    summary: "A massive platform for planning, differentiation, and student support, widely used in K-12 education.",
    tags: ["Planning", "K-12 Education"],
    dateAdded: "2026-02-03",
    author: "MagicSchool",
    year: 2023,
  },
  {
    id: "1770143100017-canva",
    title: "Canva Magic Studio",
    type: "link",
    url: "https://www.canva.com/",
    thumbnail: "",
    summary: "AI-powered design suite within Canva for generating presentations, images, and videos.",
    tags: ["Presentation Creation", "Visual Design"],
    dateAdded: "2026-02-03",
    author: "Canva",
    year: 2023,
  },
  {
    id: "1770143100018-gamma",
    title: "Gamma",
    type: "link",
    url: "https://gamma.app/",
    thumbnail: "",
    summary: "Creates beautiful presentations, documents, and webpages from text prompts in seconds.",
    tags: ["Presentation Creation", "Design"],
    dateAdded: "2026-02-03",
    author: "Gamma",
    year: 2023,
  },
  {
    id: "1770143100019-audi0p3n",
    title: "AudioPen",
    type: "link",
    url: "https://audiopen.ai/",
    thumbnail: "https://a7b19d7a245c07286533d7a21bca9acc.cdn.bubble.io/cdn-cgi/image/w=,h=,f=auto,dpr=1,fit=contain/f1689050506225x715036324823828100/Thumbnail%20New%20Jul%2011_v2.png",
    summary: "Converts spoken rambling into clear, structured text summaries, perfect for note-taking.",
    tags: ["Notes and Transcription", "Speech-to-Text"],
    dateAdded: "2026-02-03",
    author: "AudioPen",
    year: 2023,
  },
  {
    id: "1770143100020-11labs",
    title: "ElevenLabs",
    type: "link",
    url: "https://elevenlabs.io/",
    thumbnail: "https://elevenlabs.io/cover.png",
    summary: "AI audio platform capable of generating life-like voices for storytelling and accessibility.",
    tags: ["Notes and Transcription", "Voice Synthesis"],
    dateAdded: "2026-02-03",
    author: "ElevenLabs",
    year: 2022,
  },
  {
    id: "1770143100021-m33tg33k",
    title: "MeetGeek",
    type: "link",
    url: "https://www.meetgeek.ai/",
    thumbnail: "https://meetgeekpublic.s3.eu-west-1.amazonaws.com/meetgeek.ai/png/64c908e38efe9e6833b912e6_Open+Graph+Image+-+MeetGeek.png",
    summary: "Records and summarizes online meetings, emails, and calendars for efficient review.",
    tags: ["Notes and Transcription", "Summarization"],
    dateAdded: "2026-02-03",
    author: "MeetGeek",
    year: 2021,
  },
  {
    id: "1770143100022-synth3s1a",
    title: "Synthesia",
    type: "link",
    url: "https://www.synthesia.io/",
    thumbnail: "https://cdn.prod.website-files.com/65e89895c5a4b8d764c0d710/67dad5d5c238a51c2327e203_OG-Image_2025.jpg",
    summary: "Turns text input into high-quality video featuring AI avatars that \"speak\" the content.",
    tags: ["Video Creation", "Avatar Video"],
    dateAdded: "2026-02-03",
    author: "Synthesia",
    year: 2017,
  },
  {
    id: "1770143100023-h3yg3n",
    title: "HeyGen",
    type: "link",
    url: "https://www.heygen.com/",
    thumbnail: "https://cdn.sanity.io/images/pdhqcmb1/production/579e83ff34c4c832744efaedb9681d255e58dc13-1200x630.png?fit=max&auto=format",
    summary: "Create AI-generated avatar videos from text for educational and marketing purposes.",
    tags: ["Video Creation", "Avatar Video"],
    dateAdded: "2026-02-03",
    author: "HeyGen",
    year: 2020,
  },
  {
    id: "1770143100024-parlay",
    title: "Parlay",
    type: "link",
    url: "https://www.parlayideas.com/",
    thumbnail: "https://parlayideas.com/wp-content/themes/parlay14/images/share.jpg",
    summary: "Facilitates class discussions and tracks student engagement through data-driven insights.",
    tags: ["Discussion Assistants", "Classroom Management"],
    dateAdded: "2026-02-03",
    author: "Parlay",
    year: 2016,
  },
  {
    id: "1770143100025-tw33",
    title: "Twee",
    type: "link",
    url: "https://www.twee.com/",
    thumbnail: "",
    summary: "Designed for English teachers to create ESL worksheets, quizzes, and text summaries.",
    tags: ["Language Tools", "ESL"],
    dateAdded: "2026-02-03",
    author: "Twee",
    year: 2022,
  },
  {
    id: "1770143100026-l1ng0",
    title: "Lingo Teach",
    type: "link",
    url: "https://lingoteach.ai/",
    thumbnail: "https://lingoteach.ai/logo192.png",
    summary: "An AI platform built specifically to support language teachers with curriculum and content.",
    tags: ["Language Tools", "Foreign Languages"],
    dateAdded: "2026-02-03",
    author: "Lingo Teach",
    year: 2023,
  },
  {
    id: "1770143100027-t3achfx",
    title: "TeachFX",
    type: "link",
    url: "https://www.teachfx.com/",
    thumbnail: "https://framerusercontent.com/images/ZUVYv3hsUrEif0v6imx3ZRQjIJg.jpg",
    summary: "Analyzes classroom audio to provide feedback on student voice and teacher talk time.",
    tags: ["Language Tools", "Reflection"],
    dateAdded: "2026-02-03",
    author: "TeachFX",
    year: 2017,
  },
  {
    id: "1770143100028-scha1",
    title: "SchoolAI",
    type: "link",
    url: "https://schoolai.com/",
    thumbnail: "https://framerusercontent.com/images/Og1g9vg7LhVhFh5pw4i1Wb0R0.jpg",
    summary: "Includes an IEP goal generator, lesson plan tools, and personalized assistants for K-12 students.",
    tags: ["Language Tools", "IEP Support"],
    dateAdded: "2026-02-03",
    author: "SchoolAI",
    year: 2023,
  },
  {
    id: "1770143100029-handta1k",
    title: "Hand Talk",
    type: "link",
    url: "https://www.handtalk.me/en/app/",
    thumbnail: "",
    summary: "Translates text and audio into sign language using a 3D AI-powered avatar dictionary.",
    tags: ["Accessibility", "Sign Language"],
    dateAdded: "2026-02-03",
    author: "Hand Talk",
    year: 2012,
  },
  {
    id: "1770143100030-s331ngai",
    title: "Seeing AI",
    type: "link",
    url: "https://www.microsoft.com/en-us/ai/seeing-ai",
    thumbnail: "",
    summary: "Microsoft app that narrates the visual world for people with low vision by identifying people and objects.",
    tags: ["Accessibility", "Vision Support"],
    dateAdded: "2026-02-03",
    author: "Microsoft",
    year: 2017,
  },
  {
    id: "1770143100031-bra1nly",
    title: "Brainly",
    type: "link",
    url: "https://www.brainly.com/",
    thumbnail: "",
    summary: "Peer-to-peer tutoring network that uses AI to provide test prep and worksheet support.",
    tags: ["Student Tutoring", "Homework Help"],
    dateAdded: "2026-02-03",
    author: "Brainly",
    year: 2009,
  },
  {
    id: "1770143100032-khanm1g0",
    title: "Khanmigo",
    type: "link",
    url: "https://www.khanacademy.org/khanmigo",
    thumbnail: "",
    summary: "Khan Academy's AI tutor for students and assistant for teachers to support differentiation.",
    tags: ["Student Tutoring", "Socratic Learning"],
    dateAdded: "2026-02-03",
    author: "Khan Academy",
    year: 2023,
  },
  {
    id: "1770143100033-draftback",
    title: "Draftback",
    type: "link",
    url: "https://chrome.google.com/webstore/detail/draftback/icmlicpmgeokunaoenneenphkhdbdhki",
    thumbnail: "https://ssl.gstatic.com/chrome/webstore/images/chrome_web_store_v2_1200x630.png",
    summary: "Plays back the history of changes to a Google Doc to help track progress and detect plagiarism.",
    tags: ["Writing Assistants", "Integrity Tools"],
    dateAdded: "2026-02-03",
    author: "James Somers",
    year: 2014,
  },
  {
    id: "1770143100034-sparkspac3",
    title: "Sparkspace",
    type: "link",
    url: "https://www.sparkspace.ai/",
    thumbnail: "https://sparkspace.ai/sparkspace-logo.png",
    summary: "Provides real-time coaching for writing to improve student engagement and mastery.",
    tags: ["Writing Assistants", "Coaching"],
    dateAdded: "2026-02-03",
    author: "Sparkspace",
    year: 2024,
  },
  {
    id: "1770143100035-grammarly",
    title: "Grammarly",
    type: "link",
    url: "https://www.grammarly.com/",
    thumbnail: "https://static-web.grammarly.com/cms/master/public/open-graph/social-24.png",
    summary: "Widely used AI tool for grammar correction, tone adjustment, and writing improvement.",
    tags: ["Writing Assistants", "Grammar"],
    dateAdded: "2026-02-03",
    author: "Grammarly",
    year: 2009,
  },
  {
    id: "1770143100036-packback",
    title: "Packback",
    type: "link",
    url: "https://www.packback.co/",
    thumbnail: "https://packback.co/wp-content/uploads/2025/06/topimg-1.png",
    summary: "Inquiry-based discussion and writing feedback platform designed for higher ed and K-12.",
    tags: ["Writing Assistants", "Student Engagement"],
    dateAdded: "2026-02-03",
    author: "Packback",
    year: 2014,
  },
]
  {
    id: "1770255395555-ucoysd3n1",
    title: "Human-Centered Design Taxonomy Case Study",
    type: "pdf",
    url: "https://drive.google.com/file/d/1pVW3BAJnahworo2kvt93_48iYcgyBEJg/view?usp=sharing",
    thumbnail: "https://invite.illinois.edu/pdf-thumbnail.jpg",
    summary: "The Human-Centered Design approach we'll be using.",
    tags: ["Examples", "Prototyping", "User Research"],
    dateAdded: "2026-02-05",
    author: "Lawrence et al",
    year: 2024,
  },
  {
    id: "1770169869598-4ob0rq04e",
    title: "Figma Animation Tutorials",
    type: "video",
    url: "https://www.youtube.com/playlist?list=PLBblYKb7F1vr1EOc_ber1cuYpjmefGZZx",
    thumbnail: "https://i.ytimg.com/vi/m89q-wXm3mI/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCc34XPQiUiU-WeNb2GR7yjscY2vw&days_since_epoch=20488",
    summary: "Find descriptions of animations to use when vibe coding among these tutorials.\n\nIn this playlist, you'll find all the prototyping, micro-interactions and animation I have done using Figma",
    tags: ["Prototyping", "Figma", "Tutorial", "Examples", "Vibe Coding"],
    dateAdded: "2026-02-04",
    author: "YouTube",
    year: 2026,
  },
  {
    id: "1770142286776-675gzd3sk",
    title: "The Prompt Report: A Systematic Survey of Prompt Engineering Techniques",
    type: "pdf",
    url: "https://drive.google.com/file/d/1WCm_R5A5X1xo8lG7hKAcoNrWx3AmwGIh/view?usp=sharing",
    thumbnail: "https://invite.illinois.edu/pdf-thumbnail.jpg",
    summary: "Generative Artificial Intelligence (GenAI) systems are increasingly being deployed across diverse industries and research domains. Developers and end-users interact with these systems through the use of prompting and prompt engineering. Although prompt engineering is a widely adopted and extensively researched area, it suffers from conflicting terminology and a fragmented ontological understanding of what constitutes an effective prompt due to its relatively recent emergence. We establish a structured understanding of prompt engineering by assembling a taxonomy of prompting techniques and analyzing their applications. We present a detailed vocabulary of 33 vocabulary terms, a taxonomy of 58 LLM prompting techniques, and 40 techniques for other modalities. Additionally, we provide best practices and guidelines for prompt engineering, including advice for prompting engineering ChatGPT and other state-of-the-art (SOTA) LLMs. We further present a meta-analysis of the entire literature on natural language prefix-prompting. As a culmination of these efforts, this paper presents the most comprehensive survey on prompt engineering to date.",
    tags: ["Prompting Techniques", "LLM", "Multimodal Ai"],
    dateAdded: "2026-02-03",
    author: "Several Universities",
    year: 2025,
    ratingSum: 3,
    ratingCount: 1,
    userRating: 3,
  },
  {
    id: "1770142134882-i93knyox0",
    title: "Vibe Coding Fundamentals in 19 Minutes With Emergent AI",
    type: "video",
    url: "https://youtu.be/sdH7YPAmHes",
    thumbnail: "https://img.youtube.com/vi/sdH7YPAmHes/maxresdefault.jpg",
    summary: "In this video, I build a fully functional SaaS-style web app from scratch using vibe coding—no traditional coding required. I walk through creating a production-ready tool with real integrations like LLMs for text, Nano Banana Pro for image generation, and Stripe for payments, all wrapped in a polished, modern UI. You'll see how Emergent's agentic vibe coding system plans, builds, tests, and debugs the app through simple prompts, plus best practices for writing effective prompts, iterating on features, and fixing issues efficiently. This serves both as a full build demo and a practical vibe coding tutorial you can apply to your own projects.",
    tags: ["Vibe Coding", "Tutorial", "Prompting Techniques"],
    dateAdded: "2026-02-03",
    author: "Futurepedia",
    year: 2025,
  },
  {
    id: "1770142087124-su7qw9jzf",
    title: "Every AI Coding Platform Has a Prompting Guide, You Only Need One",
    type: "link",
    url: "https://buildtolaunch.substack.com/p/complete-guide-to-prompting-ai-coding-tools",
    thumbnail: "https://substackcdn.com/image/fetch/$s_!DBpi!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F74c34ce3-9a52-4a30-915a-cad8342088d7_1536x1024.png",
    summary: "Most prompt engineering advice is overcomplicated. The platforms emphasize their unique features, but when you strip away the marketing, they're all telling you the same thing in different words.\n\nThat means you don't need to learn nine different prompting systems. You need to master one and adapt as you go.",
    tags: ["Vibe Coding", "Tutorial", "Methodology"],
    dateAdded: "2026-02-03",
    author: "Jenny Ouyang",
    year: 2026,
  },
  {
    id: "1770141965765-ax87zqein",
    title: "Thematic Analysis with ChatGPT - full analysis from Codes to Themes",
    type: "video",
    url: "https://youtu.be/woJ2ztlkWPk",
    thumbnail: "https://img.youtube.com/vi/woJ2ztlkWPk/maxresdefault.jpg",
    summary: "I explain how to analyse Qualitative data with ChatGPT, and how to make sure that the analysis is credible, valid, ethical, and academic. We ensure that by keeping audit trail and breaking the analysis down into stages (Initial, Open coding - Focused, Axial coding - Theme development). You can also do Braun and Clarke's 6 step approach this way, and you can use any AI (large language model) like Claude or Gemini to do this data analysis",
    tags: ["User Research", "Tutorial", "Chatgpt", "LLM", "Data Analysis", "Qualitative Methods", "Xai"],
    dateAdded: "2026-02-03",
    author: "Dr Kriukow",
    year: 2025,
  },
  {
    id: "1770141888181-rv81e4qc0",
    title: "Data Plus Theory Equals Codebook: Leveraging LLMs for Human-AI Code- book Development",
    type: "pdf",
    url: "https://drive.google.com/file/d/1BLBwoZHEsSyigJlFdj9Y6-MH5RTBPH8X/view?usp=sharing",
    thumbnail: "https://invite.illinois.edu/pdf-thumbnail.jpg",
    summary: "Recent research has explored the use of Large Language Models (LLMs) to develop qualitative codebooks, mainly for inductive work with large datasets, where manual review is impractical. Although these efforts show promise, they often neglect the theoretical grounding essential to many types of qualitative analysis. This paper investigates the potential of GPT-4o to support theory-informed codebook development across two educational contexts. In the first study, we employ a three-step approach - drawing on Winne & Hadwin's and Zimmerman's Self-Regulated Learning (SRL) theories, think-aloud data, and human refinement - to evaluate GPT-4o's ability to generate high-quality, theory-aligned codebooks. Results indicate that GPT-4o can effectively leverage its knowledge base to identify SRL constructs reflected in student problem-solving behavior. In the second study, we extend this approach to a STEM game-based learning context guided by Hidi & Renninger's four-phase model of Interest Development. We compare four prompting strategies: No theories provided, theories named, full references given, and full-text theory papers supplied. Human evaluations show that naming the theory without including full references produced the most practical and usable codebook, while supplying full papers to the prompt enhanced theoretical alignment but reduced applicability. These findings suggest that GPT-4o can be a valuable partner in theory-driven qualitative research when grounded in well-established frameworks, but that attention to prompt design is required. Our results show that widely available foundation models - trained on large-scale open web and licensed datasets - can effectively distill established educational theories to support qualitative research and codebook development. The code for our codebook development process and all the employed prompts and codebooks produced by GPT are available for replication purposes at: https://osf.io/g3z4x",
    tags: ["User Research", "LLM", "Data Analysis", "Qualitative Methods", "Examples"],
    dateAdded: "2026-02-03",
    author: "Zambrano et al.",
    year: 2026,
  },
  {
    id: "1770141793381-fuwxxf9e3",
    title: "Exploring Differences Between Hybrid GPT-Human and Human-Created Qualitative Codebooks in an Educational Game",
    type: "pdf",
    url: "https://drive.google.com/file/d/18xMWDwbkafH6rgD39vgTi1LMNATnyK5o/view?usp=sharing",
    thumbnail: "https://invite.illinois.edu/pdf-thumbnail.jpg",
    summary: "This study explores the ability of GPT-4 working together with humans to generate a codebook to analyze scientific observations from middle school learners in the What-if Hypothetical Implementations in Minecraft (WHIMC) project. It compares this Hybrid codebook to one fully developed by Humans using a variety of techniques to evaluate how the codes developed by each approach relate to one another and to external measures of student interest. Results show that the Hybrid GPT-Human codes consist of broader categories that align more consistently with the external interest metrics, whereas the Human codes offer finer-grained insights into specific student behaviors. However, the complementary insights offered by each suggest that combining both approaches could improve our understanding of student engagement and inform more effective strategies in educational game design and intervention.",
    tags: ["User Research", "LLM", "Data Analysis", "Qualitative Methods"],
    dateAdded: "2026-02-03",
    author: "Liu et al",
    year: 2025,
  },
  {
    id: "1770141711433-6dyc88txf",
    title: "Accelerating Research with Synthetic Users",
    type: "video",
    url: "https://youtu.be/sW42UxpEs00",
    thumbnail: "https://img.youtube.com/vi/sW42UxpEs00/maxresdefault.jpg",
    summary: "In this talk, you'll explore the fast-emerging world of synthetic users—realistic, AI-powered personas you can create, interview, and learn from instantly. While they don't replace human-based research, they are a new essential augmentation to your research practice. Whether you're exploring ideas, testing early concepts, or building alignment across teams, synthetic users offer a scalable, low-risk way to accelerate your work. You'll leave this session with practical techniques you can apply immediately—even while you're watching. Synthetic users are a new, and often, controversial tool in AI-driven research. But if you're not exploring this space, you're missing a critical advantage in today's evolving research landscape.",
    tags: ["User Research", "Tutorial", "Personas", "Synthetic Data"],
    dateAdded: "2026-02-03",
    author: "UX Researchers' Guild",
    year: 2025,
  },
  {
    id: "1770141678457-oa54g3tec",
    title: "The New Playbook for Innovation: Stingray Model - Net Group",
    type: "link",
    url: "https://netgroup.com/blog/stingray-model/",
    thumbnail: "https://netgroup.com/wp-content/uploads/2025/01/Stingray-Model-Cover.png",
    summary: "Explore how the Stingray Model leverages AI innovation to streamline processes, enhance ROI, and turn ambitious ideas into reality for any team.",
    tags: ["Methodology", "User Research", "Synthetic Data"],
    dateAdded: "2026-02-03",
    author: "Net Group",
  },
  {
    id: "1770141652410-t9pf71dia",
    title: "But what is a neural network? | Deep learning chapter 1",
    type: "video",
    url: "https://youtu.be/aircAruvnKk?list=PLWV_-b7p7_7BqN6XQXSVDkXzDBiCyCJqa",
    thumbnail: "https://img.youtube.com/vi/aircAruvnKk/maxresdefault.jpg",
    summary: "What are the neurons, why are there layers, and what is the math underlying it?",
    tags: ["Ai Principles"],
    dateAdded: "2026-02-03",
    author: "3Blue1Brown",
    year: 2017,
  },
  {
    id: "1770141522998-ev3iex64f",
    title: "Transformers, the tech behind LLMs | Deep Learning Chapter 5",
    type: "video",
    url: "https://www.youtube.com/watch?v=wjZofJX0v4M",
    thumbnail: "https://img.youtube.com/vi/wjZofJX0v4M/maxresdefault.jpg",
    summary: "Breaking down how Large Language Models work, visualizing how data flows through.",
    tags: ["LLM", "Ai Principles"],
    dateAdded: "2026-02-03",
    author: "3Blue1Brown",
    year: 2024,
  },
  {
    id: "1770141463636-zod4r4l0f",
    title: "Assigning AI: Seven Ways of Using AI in Class",
    type: "link",
    url: "https://www.oneusefulthing.org/p/assigning-ai-seven-ways-of-using",
    thumbnail: "https://substackcdn.com/image/fetch/$s_!EIf_!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5ff002bc-7dfd-4c76-8acb-b0d4eef750e8_1376x864.png",
    summary: "In the paper, we actually discuss seven different ways to use AI in classrooms: AI-tutor, for increasing knowledge, AI-coach for increasing metacognition, AI-mentor to provide balanced, ongoing feedback, AI-teammate to increase collaborative intelligence, AI-tool for extending student performance, AI-simulator to help with practice, and AI-student to check for understanding. You can see them in the table, but I want to focus on two of these in this post. One that is easy to incorporate into school or work, but also a preview of the most risky, and potentially transformative, approach.",
    tags: ["Prompting Methods", "LLM", "Evaluation"],
    dateAdded: "2026-02-03",
    author: "Ethan Mollick",
  },
  {
    id: "1770141391181-i2k6kcagg",
    title: "Making Omnichannel Continuous Discovery with AI - Interview with Jeff Erickson, Viable | AI 4 UX",
    type: "video",
    url: "https://youtu.be/71wiuoFRd-Y",
    thumbnail: "https://img.youtube.com/vi/71wiuoFRd-Y/maxresdefault.jpg",
    summary: "In this installment of AI for UX, we sit down with Jeff Erickson, Co-Founder and Chief Product Officer of Viable. We discuss the combination of analyzing many customer data sources with innovative data collection techniques including automating the interview process to gather rich, qualitative data more efficiently at scale.",
    tags: ["User Research", "Data / Quantitative", "Qualitative Methods", "Examples"],
    dateAdded: "2026-02-03",
    author: "Brilliant Experience",
    year: 2024,
  },
  {
    id: "1770141314412-nm24bs0nk",
    title: "Make UX Research Faster with AI: AI for UX with Max Fergus, UserCue",
    type: "video",
    url: "https://www.youtube.com/watch?v=BL0qKDvg8XI",
    thumbnail: "https://img.youtube.com/vi/BL0qKDvg8XI/maxresdefault.jpg",
    summary: "In this installment of AI 4 UX, we sit down with Max Fergus, the CEO of UserCue. He talks with us all about future of UX research and how UserCue offers dynamic AI moderated interviews and analysis at scale.",
    tags: ["User Research", "Qualitative Methods", "Interviews", "Examples"],
    dateAdded: "2026-02-03",
    author: "Brilliant Experience",
    year: 2024,
  },
  {
    id: "1770141236033-epxs9zyes",
    title: "7 AI Skills You Need NOW for 2026",
    type: "video",
    url: "https://youtu.be/kHD3M_9uMs4",
    thumbnail: "https://img.youtube.com/vi/kHD3M_9uMs4/maxresdefault.jpg",
    summary: "Learn the 7 essential ai skills you need to master in 2026 to stay ahead in your work and business. This comprehensive AI tutorial covers how to reduce AI hallucinations and leverage the LLM Council method for better results, focusing on next generation skills like ai automation and ai workflows to futureproof yourself. Mastering these techniques and adopting adaptive thinking will help you leverage AI more effectively for content creation, business automation, and creative work.",
    tags: ["Tutorial", "Ai Literacy"],
    dateAdded: "2026-02-03",
    author: "Futurepedia",
    year: 2026,
  },
  {
    id: "1770141205170-rexx8koqj",
    title: "How to Use NotebookLM Better than 99% of People",
    type: "video",
    url: "https://youtu.be/OdCmZvPdr4s",
    thumbnail: "https://img.youtube.com/vi/OdCmZvPdr4s/maxresdefault.jpg",
    summary: "In this video, I'm giving you the complete NotebookLM masterclass—everything you need to go from beginner to expert. NotebookLM is hands down the most underrated AI tool out there, and most people have no idea what it's actually capable of. I'll walk you through the entire interface, show you how to build research notebooks with cited sources that eliminate hallucinations, demonstrate every Studio Panel feature (podcasts, infographics, slide decks, and more), reveal how to connect it all to Gemini for custom AI assistants, and share creative use cases that go way beyond just research and learning. Whether you're using it for work, personal projects, or just trying to learn something new, this guide will show you how to unlock the full power of NotebookLM.",
    tags: ["Tutorial", "Research", "RAG", "Information Stream"],
    dateAdded: "2026-02-03",
    author: "Futurepedia",
    year: 2026,
  },
  {
    id: "1770141153067-o7ksn8ccb",
    title: "Google AI Studio: From Prompt to Prototype",
    type: "video",
    url: "https://www.youtube.com/playlist?list=PLIivdWyY5sqIagw3_50GeVHIwcUoOwTa7",
    thumbnail: "https://img.youtube.com/vi/placeholder/maxresdefault.jpg",
    summary: "You'll get a crash course on AI Studio's awesome features, master the art of crafting prompts that actually work, and explore the mind-blowing world of multimodal AI. Think image and video analysis, real-time streaming, and more right at your fingertips! You'll learn how to build a real, working AI-powered app from scratch and get set up with API keys so you can deploy your own creations to the world.",
    tags: ["Prototyping", "Gemini", "Tutorial", "Vibe Coding"],
    dateAdded: "2026-02-03",
    author: "Google Cloud Tech",
    year: 2025,
  },
  {
    id: "1770141088749-8g63h9h66",
    title: "Cognimates Copilot - AI Assistant for Kids' Scratch Programming",
    type: "link",
    url: "https://cognimates-copilot.replit.app/#demo",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=300&fit=crop",
    summary: "No description provided.",
    tags: ["Examples", "Block Code", "Learning Environment"],
    dateAdded: "2026-02-03",
    author: "Cognimates",
    year: 2025,
  },
  {
    id: "1770141041037-vleztz459",
    title: "The Hybrid Builder | LinkedIn",
    type: "link",
    url: "https://www.linkedin.com/newsletters/the-hybrid-builder-7343716216856858624/",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=300&fit=crop",
    summary: "BuidToLearn and LearnToBuild —co-created with AI - a newsletter / blog mostly about things Claude can do",
    tags: ["Tutorial", "Claude", "Skills", "Vibe Coding"],
    dateAdded: "2026-02-03",
    author: "Vishal Sachdev",
    year: 2026,
  },
  {
    id: "1770140996624-r3mnxk9t9",
    title: "Midjourney Video: My FULL Course (15 Lessons)",
    type: "video",
    url: "https://www.youtube.com/watch?v=Dkj7Jqejfz0&list=PLWV26Jk6VfmSt2cmvDDZzv96BN1okWP6Y",
    thumbnail: "https://img.youtube.com/vi/Dkj7Jqejfz0/maxresdefault.jpg",
    summary: "How to create video with Midjourney",
    tags: ["Midjourney", "Tutorial", "Multimodal Ai"],
    dateAdded: "2026-02-03",
    author: "Future Tech Pilot",
    year: 2025,
  },
  {
    id: "1770140965509-pa9q7al9w",
    title: "The ULTIMATE Beginners Guide to Midjourney in 2025",
    type: "video",
    url: "https://youtu.be/vUj4VNXXC1c",
    thumbnail: "https://img.youtube.com/vi/vUj4VNXXC1c/maxresdefault.jpg",
    summary: "A guide to creating images with Midjourney",
    tags: ["Midjourney", "Tutorial", "Multimodal Ai"],
    dateAdded: "2026-02-03",
    author: "Future Tech Pilot",
    year: 2025,
  },
  {
    id: "1770106402761-hir6gff5j",
    title: "Four Principles of Explainable Artificial Intelligence",
    type: "pdf",
    url: "https://drive.google.com/file/d/1HT12NnDKsF4pKK1PLCnoWHM-BnNJarvM/view?usp=sharing",
    thumbnail: "https://invite.illinois.edu/pdf-thumbnail.jpg",
    summary: "We introduce four principles for explainable artificial intelligence (AI) that comprise fundamental properties for explainable AI systems. We propose that explainable AI systems deliver accompanying evidence or reasons for outcomes and processes; provide explanations that are understandable to individual users; provide explanations that correctly reflect the system's process for generating the output; and that a system only operates under conditions for which it was designed and when it reaches sufficient confidence in its output. We have termed these four principles as explanation, meaningful, explanation accuracy, and knowledge limits, respectively. Through significant stakeholder engagement, these four principles were developed to encompass the multidisciplinary nature of explainable AI, including the fields of computer science, engineering, and psychology. Because one-sizefits-all explanations do not exist, different users will require different types of explanations. We present five categories of explanation and summarize theories of explainable AI. We give an overview of the algorithms in the field that cover the major classes of explainable algorithms. As a baseline comparison, we assess how well explanations provided by people follow our four principles. This assessment provides insights to the challenges of designing explainable AI systems.",
    tags: ["Xai", "Methodology", "Ai Literacy", "Ai Principles"],
    dateAdded: "2026-02-03",
    author: "NIST",
    year: 2021,
  },
]

// Base popular tags are now dynamically generated from actual resource tags

export interface TagWithCount {
  tag: string
  count: number
}

// Get popular tags - generated from actual tags used in the library, sorted by frequency
// Only returns tags with more than 3 items
export const getPopularTags = (resourceList: Resource[] = resources, limit: number = 20): TagWithCount[] => {
  // Count tag frequency in resources
  const tagCounts: Record<string, number> = {}
  resourceList.forEach(resource => {
    resource.tags.forEach(tag => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1
    })
  })
  
  // Filter tags with more than 3 items, sort by frequency and return top tags
  return Object.entries(tagCounts)
    .filter(([_, count]) => count > 3)
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([tag, count]) => ({ tag, count }))
}
